config/routes.rb
Rails.application.routes.draw do
  

  
  get 'message/index'
  get 'signup/view', to: 'signup#view'
  post 'signup/create', to: 'signup#create'
  root 'login_page#login'
  
  post 'login/create', to: 'login_page#create'
  
  post 'result/show'
  get 'main_page/create'
  get 'main_page/show'
  post 'main_page/create'
  get 'main_page/update', to: 'main_page#update'
  get 'main_page/edit'
  get 'main_page/delete', to: 'main_page#delete'
  
  get 'login_page/login'

  get '/auth/:provider/callback', to: 'twitter_callback#create'
  delete '/logout', to: 'twitter_callback#destory'
  #カレンダー表示用
  get 'events', to: 'main_page#events'
  
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/login_page_controller.rb
class LoginPageController < ApplicationController
  def login
      @user = User.new
   # # request.env['omniauth.auth']にユーザのTwitter認証情報が格納されている
   #  user_data = request.env['omniauth.auth']
   #  logger.debug("debug!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
   #  logger.debug(user_data.inspect)
   #  logger.debug("debug Complete!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
   #  session[:nickname] = user_data[:info][:nickname]
#   redirect_to main_page_show_path, notice: 'ログインしました'
  end
  
  def create
      if params[:user][:user_name] == nil || params[:user][:password] == nil
          flash[:danger] = "Please input the Your name or Password"
          redirect_to :root
      
      end
      user = User.find_by(user_name: params[:user][:user_name])
      
      if user && user.authenticate(params[:user][:password])
          session[:user_id] = user.id
          session[:nickname] = user.user_name
          redirect_to main_page_show_path
      else
          flash[:danger] = "Wrong Username or Password. <br> Please confirm Username or Password"
          redirect_to :root
      end
      
  end
end

app/helpers/login_page_helper.rb
module LoginPageHelper
end

app/views/login_page/login.html.erb
<%= stylesheet_link_tag 'user', media: 'all', 'data-turbolinks-track' => true %>

<div id="login">
  <div>
    <%= image_tag 'pjTimeTable.png'%>
  </div>
<%= form_for @user, url: login_create_path do |f| %>
  <%# flash.each do |message_type, message| %> 
            <!--<div class="alert alert-<%#= message_type %>" role="alert">
              <%#= message.html_safe %>
            </div>-->
  <%# end %>
  
<div id="idInput"class="input-group input-group-lg">
  <div class="input-group-prepend">
    <span class="input-group-text fontawesome-user" id="inputGroup-sizing-default">
      <%#= f.label :user_name, "Your name" %>
    </span>
    <%= f.text_field :user_name, :id => "user", :class => "form-control", :placeholder => "your nickname" %>
  </div>
</div>

<div class="input-group input-group-lg">
  <div class="input-group-prepend">
    <span class="input-group-text form-group fontawesome-lock" id="inputGroup-sizing-default">
      <%#= f.label :password, "Password" %> 
    </span>
     <%= f.password_field :password, :class => "form-control", :placeholder => "Password" %> 
  </div>
</div>
            <%= f.submit "Login", class: "btn btn-success btn-lg btn-block" %>
            
<% end %>

        <!--<span class="fontawesome-user"></span>-->
        <!--  <input type="text" id="user" placeholder="Username">-->
       
        <!--<span class="fontawesome-lock"></span>-->
        <!--  <input type="password" id"pass" placeholder="Password">-->
        
        <!--<input type="button" value="Login" id="ref">-->
        <%= link_to 'Sign up', signup_view_path, :class => "btn btn-info btn-lg btn-block" %>
        <%= link_to 'Sign in with Twitter', '/auth/twitter', :class => "btn btn-primary btn-lg btn-block" %>
      
      </div>