config/routes.rb
Rails.application.routes.draw do
  

  
  get 'message/index'
  get 'signup/view', to: 'signup#view'
  post 'signup/create', to: 'signup#create'
  root 'login_page#login'
  
  post 'login/create', to: 'login_page#create'
  
  post 'result/show'
  get 'main_page/create'
  get 'main_page/show'
  post 'main_page/create'
  get 'main_page/update', to: 'main_page#update'
  get 'main_page/edit'
  get 'main_page/delete', to: 'main_page#delete'
  
  get 'login_page/login'

  get '/auth/:provider/callback', to: 'twitter_callback#create'
  delete '/logout', to: 'twitter_callback#destory'
  #カレンダー表示用
  get 'events', to: 'main_page#events'
  
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  def view
    @user = User.new
  end

  def create
    begin
      #Error handling Start!
      newUser = User.new(user_params)
      if newUser.valid?
          newUser.save!
          flash[:success] = "Created Your account !"
          redirect_to :root
      else 
          flash[:danger] = "password and password_confirmation are different.<br> Please make sure password"
          redirect_to signup_view_path
      end
    rescue => e #Error handling! 想定するエラーとしては、すでに存在しますなどのSQLエラー
        p e
        flash[:danger] = "Aleady exists Username"
        redirect_to signup_view_path
    end
     
  end

  private
    def user_params
        params.require(:user).permit(:user_name, :password, :password_confirmation)
    end
  
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signup/create.html.erb
<h1>Signup#create</h1>
<p>Find me in app/views/signup/create.html.erb</p>

app/views/signup/view.html.erb
<%= form_for @user, url: signup_create_path do |f| %>
  <div id="signup">

  <% flash.each do |message_type, message| %> 
            <div class="alert alert-<%= message_type %>" role="alert">
              <%= message.html_safe %>
            </div>
<% end %>
  <h1 class="display-3">SIGN UP</h1>
  <div class="form-group">
    <%= f.label :user_name, "Your name" %>
    <%= f.text_field :user_name, :class => "form-control", :placeholder => "your nickname" %>
  </div>
  <div class="form-group">
      <%= f.label :password, "Password" %> 
      <%= f.password_field :password, :class => "form-control", :placeholder => "Password" %> 
   </div>
  <div class="form-group">
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, :class => "form-control", :placeholder => "Password Confirmation" %>

  </div>
  <%= f.submit "Create my account", class: "btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>