config/routes.rb
Rails.application.routes.draw do
  

  
  get 'message/index'
  get 'signup/view', to: 'signup#view'
  post 'signup/create', to: 'signup#create'
  root 'login_page#login'
  
  post 'login/create', to: 'login_page#create'
  
  post 'result/show'
  get 'main_page/create'
  get 'main_page/show'
  post 'main_page/create'
  get 'main_page/update', to: 'main_page#update'
  get 'main_page/edit'
  get 'main_page/delete', to: 'main_page#delete'
  
  get 'login_page/login'

  get '/auth/:provider/callback', to: 'twitter_callback#create'
  delete '/logout', to: 'twitter_callback#destory'
  #カレンダー表示用
  get 'events', to: 'main_page#events'
  
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
  
  def delete
    logger.debug("!!!!!! Delete Data !!!!")
    logger.debug(params[:id])
    @event = Event.find_by(id: params[:id])
    @event.destroy
      respond_to do |format|
        format.html { redirect_to '/main_page/show', notice: 'Event was successfully deleted.' }
        format.js { @status = "deleted" }
      end
  end
  
  def edit
     @event = Event.find_by(id: params[:id])
     logger.debug("Edit Debug event !!!!!!!!!!1")
     logger.debug(@event.inspect)
  end
  
  def update
    @event = Event.find(params[:event][:id])
    time_s = params[:date] + " "+ params[:event][:start] #concat date and time_from
    time_e = params[:date] + " " + params[:event][:end] #concat date and time_to
    time_s.to_datetime #convert String to Datetime
    time_e.to_datetime #convert String to Datetime
    @event.update(start:time_s, end:time_e, title:params[:event][:title],
      category_id:params[:event][:category_id],useless_flag:params[:event][:useless_flag], 
      user_id: current_user.id)
      #return redirect_to main_page_show_path
      respond_to do |format|
        format.html { redirect_to main_page_show, notice: 'User was successfully created.' }
        format.js { @status = "created" }
      end      
  end

  def show
    #@category = Category.all
    @resultpr = Resultpr.new
    if(params[:event_sonzai_flg] == "1") then
      @event = Event.find(params[:id])
      @event.start = @event.start.to_s
      @event.end = @event.end.to_s
       render :json => @event
    else
      @event = Event.new 
    end
    logger.debug("Debug event_cont !!!!!!!!!!1")
    logger.debug(@event.inspect)
  end
    
  def create
    
    logger.debug(current_user)
    time_s = params[:date] + " "+ params[:event][:start] #concat date and time_from
    time_e = params[:date] + " " + params[:event][:end] #concat date and time_to
    time_s.to_datetime #convert String to Datetime
    time_e.to_datetime #convert String to Datetime
    
    ## 入力値制御
    if params[:date].blank?
      # 日時必須入力
      logger.debug("falsh処理！！！！！！！！！")
        respond_to do |format|
          format.js { flash[:danger] = "日時は必須入力です。" ,
            @status = "fail"
          }
        end       
    elsif params[:event][:start].blank?
      # 開始時刻必須入力
      logger.debug("falsh処理！！！！！！！！！")
        respond_to do |format|
          format.js { flash[:danger] = "開始時間は必須入力です。" ,
            @status = "fail"
          }
        end    
    elsif params[:event][:end].blank?
      # 終了時刻必須入力
      logger.debug("falsh処理！！！！！！！！！")
        respond_to do |format|
          format.js { flash[:danger] = "終了時間は必須入力です。" ,
            @status = "fail"
          }
        end   
    elsif params[:event][:title].blank?
      # 予定内容必須入力
      logger.debug("falsh処理！！！！！！！！！")
        respond_to do |format|
          format.js { flash[:danger] = "予定内容は必須入力です。" ,
            @status = "fail"
          }
        end   
    elsif params[:event][:category_id].blank?
      # カテゴリー必須入力
      logger.debug("falsh処理！！！！！！！！！")
        respond_to do |format|
          format.js { flash[:danger] = "カテゴリーは必須入力です。" ,
            @status = "fail"
          }
        end           
    elsif time_s > time_e
      logger.debug("falsh処理！！！！！！！！！")
        respond_to do |format|
          format.js { flash[:danger] = "終了時間には開始時間以降の値を入力してください。" ,
            @status = "fail"
          }
        end
      # redirect_to message_index_path   
      
    else
      ## 入力値にエラーがない場合
      
      ## 更新処理
      if params[:event][:id].blank? != true
        return self.update
      end      
      
      ## 登録処理
      logger.debug("現在のユーザー確認！！！！！！！！！")
      logger.debug(current_user.inspect)
      event = Event.new(start:time_s, end:time_e, title:params[:event][:title],
      category_id:params[:event][:category_id],useless_flag:params[:event][:useless_flag], 
      user_id: current_user.id )
      
      logger.debug(event.inspect)
      begin
        if event.save! #save the object data to DB　=> Create id and created_time, updated_time automatically.
        # redirect_to main_page_show_path
          respond_to do |format|
            format.html { redirect_to main_page_show, notice: 'User was successfully created.' }
            format.js { @status = "created" }
          end
        end
        rescue Exception => e
          respond_to do |format|
            format.html { redirect_to main_page_show, notice: "User wasn't successfully created." }
            format.js { flash[:danger] = "この時間帯には入力できません。" ,
            @status = "fail" }
          end
        end
    end
  end

  #DBの値をfulcalendarに表示する処理
  def events
    @event = Event.where(user: current_user)
    logger.debug("!!!! Fullcalendar 処理をしています。 !!!!!")
    respond_to do |format|
      format.json{
        render json:
        @event.to_json(
          only: [:title,:start,:end, :id]
          )
      }
    end
  end
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/views/main_page/_edit.html.erb
<div  class="modal fade modalEdit" tabindex="-1" role="dialog" aria-labelledby="eventModalLabel" aria-hidden="true">
    <%= render partial: 'eventModal' %>
</div>
<!-- newEventAndDateModal div End -->

app/views/main_page/_eventModal.html.erb
<% require "date" %>

<div id="newEventAndDateModal" class="modal fade " tabindex="-1" role="dialog" aria-labelledby="eventModalLabel" aria-hidden="true">
        <!-- newEventAndDateModal Start -->
        
          <div class="modal-dialog" role="document">
            <div class="modal-content">
                
              <div class="modal-header">
                <div class="col-xs-6">
                  <span><h2 class="modal-title" id="eventModalLabel">イベントの入力</h2></span>
                </div>
                  <div class="col-xs-6">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <h4><span aria-hidden="true">&times;</span></h4>
                  </button>
                </div>
              </div><!-- modal-header end -->
              
              <div class="modal-body">
    <%= form_for @event, :url => {:action => :create }, remote: true do |f| %> <!-- form_for start from modal-body to modal-footer -->
      
                <div class="dateSection">
                  <span><%= date_field_tag :date, :readonly => true  %></span>
                </div>
                <div class="modalInputArea">
                <div class="newEventSection_time left_line_modal bottom_line">
                  <span><%= f.label :start, "開始時間" %></span>
                  <span><%= f.time_field :start, :readonly => true %></span>
                  <!--？？-->
                  <span>〜</span>
                  <!--<span>終了時間</span>-->
                  <span><%= f.label :end, "終了時間" %></span>
                  <span><%= f.time_field :end, :readonly => true%></span>
            <!-- エラーメッセージdahun start-->
            <div id="flash_messages"></div>
            <!-- エラーメッセージ dahun end-->
            <!-- create.js.erb によって動的に追加される。-->
             
                </div>
                <div class="newEventSection_content left_line_modal bottom_line">
                  <span><%= f.label :title, "予定を入力してください" %></span>
                  <%= f.text_field :title %>
                 
                </div>
                <div class="left_line_modal bottom_line">
                  <span><%= f.label :category, "カテゴリーを入力してください" %></span>
                  <%= f.collection_select :category_id, Category.all, :id, :category_val, {:selected => 1}%>
                </div>
                <div class="form-check newEventSection_uselessAndCheck left_line_modal bottom_line">
                  <span><%= f.label :useless_flag, "無駄な時間でしたか？チェックしてください。", :class => "form-check-label" %></span>
                  <span><%= f.check_box :useless_flag, :class => "form-check-input" %></span>
                </div>
                
                </div><!-- modal-body end -->
              </div>  <!-- modalInputArea -->
                <div class="modal-footer">
                  <%= f.hidden_field :id %>
                  <%= f.button "Cancel", :class => "btn btn-default", "data-dismiss": "modal" %>
                  <%= f.submit "Save", :class => "btn btn-primary" %>
        <% end %>
                </div><!-- modal-footer end -->
            </div><!-- modal-content end -->
          </div> <!-- modal-dialog end -->
</div>

app/views/main_page/create.js.erb
<% if @status == 'fail' %>
    <!-- エラーが発生した場合、flashでエラーメッセージ表示 -->
    
    <% flash.each do |type, message| %>
      $("#flash_messages").html("<div class='alert alert-<%= type %>' role='alert'> <%= message[0] %><button type='button' class='close' data-dismiss='alert'>&times;</button> </div>")
    <% end %>
<%  elsif @status == 'created' || @status == 'deleted' %>
    <!-- エラーが発生していない場合、エラーメッセージを表示しない -->

    $("#newEventAndDateModal").modal("hide");
    var event = $.ajax("/events.json");
    console.log(event);
   $("#calendar").fullCalendar("renderEvents", event, true );
   $("#calendar").fullCalendar("refetchEvents");
   
<% end %>

app/views/main_page/show.html.erb
  <!--heaer start -->
  <header>
    <div class="page-loader">
      <div class="loader">Loading...</div>
    </div>
    <!-- nav container start -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="index.html">Main Page</a>
        </div>

        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "Logout", logout_path, :method => "DELETE", :class => "navbar-brand" %>
            </li>
        </ul>
    </div>
      </div>
      <!-- nav container end -->
    </nav>
    <div class="main">
      <section class="module bg-dark-30 about-page-header" data-background="#{asset-path('about_bg.jpg')">
        <div class="container">
          <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
              <h1 class="module-title font-alt mb-0">Main Page</h1>
            </div>
            
          </div>
        </div>
      </section>
  </header>
  <!--heaer end -->

  <!-- section start -->
  <section>
    <div class="row section_div">
      <article class="">
        <div id="logout">
          <% if session[:nickname] %>
            <span class="badge badge-success"><%= "#{session[:nickname]}さん、こんにちは" %></span>
          <% end %>
          
        </div>
      </article>
      <article class="">
        
      <div id="Report">
        <!--<form class="" action="index.html" method="post">-->
        
 <%#= form_tag result_show_path, :method => "GET" do %>
 <%= form_for @resultpr, url:result_show_path do |f| %>
        <div class="report hr-sect"> Report </div>
<!--<div id="flash_messages"></div>        -->
 <% flash.each do |message_type, message| %> <!-- dahun https://getbootstrap.com/docs/4.3/components/alerts/ -->
          <div class="alert alert-<%= message_type %>" role="alert">
            <%= message %>
          </div>
  <% end %>
        <div class="dateSpan left_line bottom_line">
        <!-- エラーメッセージnarukiyo start-->

        <!-- エラーメッセージnarukiyo end-->
          <span><%= f.label :date_span_from, "開始日", :class => "badge badge-dark" %></span>
          <!--<span>開始日</span>-->
          <span><%= f.date_field :date_span_from, :class => "dateField" %></span>
          <!--<input type="date" name="date">-->
          <span>　　</span>
          <span>～</span>
          <span>　　</span>
          <span><%= f.label :date_span_to, "終了日", :class => "badge badge-dark" %></span>
          <!--<span>終了日</span>-->
          <span><%= f.date_field :date_span_to, :class => "dateField" %></span>
          <!--<input type="date" name="date">-->
      
          <span><%= submit_tag "Result", :name => "ReportSubmit", :class => "btn btn-secondary" %></span>
<!--</form>-->
<% end %>
        </div>

      </div>
          <div class="main_article">
            <div class="timetable_head"> <h3>Time table</h3></div>
            <div id='calendar'>
  
            </div>
          </div>
      </article>
      <!-- section end-->
      <div class="col-xs-1"></div>
      <!-- section start-->
      <article class="">
        <div id= "calendar"></div>
         <%= render 'eventModal' %>
         <!-- _eventModal.html.erbを読み込む。-->
  
      <div class=""></div>


      </article>
    </div>

  </section>
  <!-- section end-->